### ISSUE TITLE
Elegoo Neptune 4 Plus/Max Head Connection File Missing

### ISSUE THREAD

**Issue by 05wrxsti** [coprint/AssemblingParts#6]
Available head connection file appears to be for the Neptune 2/3/4+ series. The printed part doesn't mate up with the Neptune 4 Plus/Max mounting bracket. The metal bracket that came with ChromaHead could work if the belt grabs were 1/2" wider or if a longer x-axis belt was provided with the kit.

**Comment by cdvankammen** [comment]
Yes please make this possible! Those connectors are not for every type!

**Comment by 05wrxsti** [comment]
> Yes please make this possible! Those connectors are not for every type!

Files for the 4 Plus/Max have been shared on discord (#assembly-parts). [Here...](https://discord.com/channels/1144633500922822656/1303965639991365662/1304990875436449863)

**Comment by 05wrxsti** [comment]
^^^
